module.exports = {
  extends: ['airbnb-base', 'prettier'],
  env: {
    jest: true,
  },
  parser: 'babel-eslint',
  plugins: ['jest'],
  rules: {
    'import/prefer-default-export': 'off',
    'jest/consistent-test-it': 'error',
    'jest/expect-expect': 'off',
    'jest/lowercase-name': 'off',
    'jest/no-alias-methods': 'error',
    'jest/no-disabled-tests': 'error',
    'jest/no-focused-tests': 'error',
    'jest/no-hooks': 'off',
    'jest/no-identical-title': 'error',
    'jest/no-jasmine-globals': 'error',
    'jest/no-jest-import': 'error',
    'jest/no-large-snapshots': 'off',
    'jest/no-test-callback': 'error',
    'jest/no-test-prefixes': 'error',
    'jest/no-test-return-statement': 'off',
    'jest/no-truthy-falsy': 'off',
    'jest/prefer-expect-assertions': 'off',
    'jest/prefer-spy-on': 'warn',
    'jest/prefer-strict-equal': 'off',
    'jest/prefer-to-be-null': 'warn',
    'jest/prefer-to-be-undefined': 'warn',
    'jest/prefer-to-contain': 'warn',
    'jest/prefer-to-have-length': 'warn',
    'jest/prefer-inline-snapshots': 'off',
    'jest/require-tothrow-message': 'off',
    'jest/valid-describe': 'error',
    'jest/valid-expect-in-promise': 'error',
    'jest/valid-expect': 'error',
    'jest/prefer-todo': 'warn',
    'no-nested-ternary': 'off',
    'no-unused-expressions': ['error', { allowTaggedTemplates: true }],
    'valid-jsdoc': [
      'error',
      {
        prefer: {
          arg: 'param',
          argument: 'param',
          return: 'returns',
        },
      },
    ],
  },
};
